# Basic look at the data





## First ggplot of the data

```{r, fig.width= 14, fig.height=13,warning=FALSE}
studio1959_2020 <- 
  ggplot(data = studiotop50, mapping =  aes(x = production,
                                                y = reorder (studios, production))) + 
  geom_point(aes(size = rating, colour = rating, check_overlap = TRUE)) + 
  geom_text(aes(label = sprintf("%.2f",rating),hjust = -0.5),frontface="bold")
                                                                                 
plot <- studio1959_2020 + scale_x_discrete(guide = guide_axis(n.dodge = 5)) +
  scale_x_continuous("Number of Total Production") + 
  theme(axis.text.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 20, face = "bold"),
        plot.tag.position = c (0.2, 0.01))
  


print(plot + labs(y = "Studio Name", tag = "Figure1: 1958-2020 No.studio's production and overallrating"))

```




## Second ggplot of the data


```{r, fig.width= 13, fig.height=12}
studio1959_2020c <- 
  ggplot(data = studiotop50, mapping =  aes(x = rating,
                                                y = reorder (studios, rating))) + 
  geom_point(aes(size = production, colour = rating, check_overlap = TRUE)) + 
  geom_text(aes(label = production),hjust = -0.5) +
  geom_text(aes(label = sprintf("%.2f",rating),hjust = +1.5))
                                                                                 
plot1 <- studio1959_2020c + scale_x_discrete(guide = guide_axis(n.dodge = 5)) +
  scale_x_continuous("Average rating") +
  theme(axis.text.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12, face = "bold"),
        plot.tag.position = c (0.2, 0.01))
  


print(plot1+labs(y = "Studio Name",tag = "Figure2: 1958-2020 ranked studio's overallrating"))

```










